### ISSUE TITLE
Add CI stuff, lint, etc

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/varo#8]
@AdrieanKhisbe If you want to take a crack at this I won't be upset :D

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe You should have proper access to this repo now.

**Comment by AdrieanKhisbe** [comment]
incomnig soon :)

**Comment by mcdonnelldean** [comment]
Make sure to add yourself to the contrib list

Kindest Regards,

Dean

**Comment by mcdonnelldean** [comment]
Closed by #9
